/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wzp_demo_serialport_SerialPort */

#ifndef _Included_wzp_demo_serialport_SerialPort
#define _Included_wzp_demo_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wzp_demo_serialport_SerialPort
 * Method:    jOpen
 * Signature: (IICII)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_wzp_demo_serialport_SerialPort_jOpen
  (JNIEnv *, jobject, jint, jint, jchar, jint, jint);

/*
 * Class:     wzp_demo_serialport_SerialPort
 * Method:    jClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_wzp_demo_serialport_SerialPort_jClose
  (JNIEnv *, jobject);

/*
 * Class:     wzp_demo_serialport_SerialPort
 * Method:    isOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_wzp_demo_serialport_SerialPort_isOpen
  (JNIEnv *, jobject);

/*
 * Class:     wzp_demo_serialport_SerialPort
 * Method:    flushBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_wzp_demo_serialport_SerialPort_flushBuffer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
